### ISSUE TITLE
Get-SdnServiceFabricClusterManifest fails when calling back to itself

### ISSUE THREAD

**Issue by arudell** [microsoft/SdnDiagnostics#158]
**Describe the bug**
Get-SdnServiceFabricClusterManifest fails when calling back to itself

**To Reproduce**
1. Connect to Network Controller and run `Get-SdnServiceFabricClusterManifest` which will fail

**Expected behavior**
Cluster Manifest should be returned back successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/18577812/211641658-b7b3acf3-152b-4cf9-baf2-abb798ab13a6.png)

**Comment by luyaof** [comment]
Is this happening on a Cluster with X509 auth or Kerberos?

**Comment by arudell** [comment]
It's happening with how the invoke command is working and just a logic issue, not anything to do with actual authentication. Fix itself is easy and I will have a fix submitted early next week.

**Comment by arudell** [comment]
@luyaof not sure best method to proceed on this. Ultimately the issue happens when you do the following:

1. Connect to NC via PSRemoting from another node
2. Run the Get-SdnServiceFabricClusterManifest command, or any other SF cmdlet without specifying a NetworkController, or specify the NetworkController you are connected into
3. Error is received, because we cannot pass our current session credentials into a new one, not without specifying -Credential

To get around this problem, need to evaluate the following:
- Update Invoke-SdnServiceFabricCommand to do either `Invoke-Command` or `Invoke-Command -ComputerName / -Sesssion` based on if NetworkController is local. This introduces other challenges, because SF requires us to use `Connect-ServiceFabricCluster` within the current runspace. All higher level commands passing through then would either need to add `Connect-ServiceFabricCluster`  before the command being executed, or get crafty on the -Arguments.
- Add more defensive blocks by detecting if we connecting into the remote runspace and block operation entirely.


Open to ideas on this one.
