### ISSUE TITLE
Typo in wiki installation step

### ISSUE THREAD

**Issue by msftJayWang** [microsoft/SdnDiagnostics#64]
The cmdlet in wiki has extra "s". The correct cmdlet appears to be "Install-SdnDiagnostic" 

![image](https://user-images.githubusercontent.com/91253562/134483040-c8d21c99-35c1-43fa-9107-756db917a5d2.png)

**Comment by arudell** [comment]
Thank you for the feedback. The name has been changed with PR #63 to fix some odd side-by-side versioning issues. Received feedback that even though goes against normal PS standards of using plural vs singular, having the name match up with the public module name was more user friendly.

If you update to 1.2109.70.132852, you will see the new changes which align to the wiki documentation.
